services:
  - type: web
    name: opengym
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    envVars:
      - key: RP_NAME
        value: openGym
      - key: DATA_DIR
        value: /app/data
